In [1]:
import pandas as pd

# Q1. Pandas version
## What's the version of Pandas that you installed?

In [2]:
pd.__version__

'2.2.2'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [4]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

# Q2. Records count
## How many records are in the dataset?

In [5]:
len(df)

2160

# Q3. Laptop brands|
## How many laptop brands are presented in the dataset?

In [19]:
len(df['Brand'].unique())

27

# Q4. Missing Value
How many columns in the dataset have missing values?

In [7]:
df.isnull().sum() > 0

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen           True
Touch           False
Final Price     False
dtype: bool

# Q5. Maximum final price
## What's the maximum final price of Dell notebooks in the dataset?

In [8]:
df_dell = df[df['Brand'] == 'Dell']
df_dell['Final Price'].max()

np.float64(3936.0)

# Q6 Median value of Screen

In [9]:
# Find median
pd.Series(df['Screen']).median()

np.float64(15.6)

In [10]:
# Find the most frequent value of the same Screen Column
# df.groupby('Screen').count()
the_most_feq_of_screen = df['Screen'].mode()[0]
the_most_feq_of_screen

np.float64(15.6)

In [11]:
# Fill data missing value with `the_most_feq_of_screen`
df['Screen'] = df['Screen'].fillna(the_most_feq_of_screen)

In [12]:
# Calculate the median again.
pd.Series(df['Screen']).median()

np.float64(15.6)

# Q7. Sum of weights

In [62]:
#Select all the 'Innjoo'
innjoo = df[df['Brand'] == 'Innjoo']

# Get field RAM, Storage, Screen
X = innjoo[['RAM', 'Storage', 'Screen']].values
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [63]:
print(X.transpose())
XT = X.transpose()

[[  8.    8.    4.    6.    6.    6. ]
 [256.  512.   64.   64.  128.  128. ]
 [ 15.6  15.6  14.1  14.1  14.1  14.1]]


In [64]:
import numpy as np
# Multiply X transpose and X
XTX = np.matmul(XT, X)
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [65]:
# Inverse
XTX_inv = np.linalg.inv(XTX)

In [68]:
# Declare array y = [1100, 1300, 800, 900, 1000, 1100]
y = [1100, 1300, 800, 900, 1000, 1100]

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w1 = np.matmul(XTX_inv, XT)
w = np.matmul(w1, y)

In [70]:
print('The result sum of w is ', w.sum())

The result sum of w is  91.2998806299555
